// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgfbpwiwxudlquomaqbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnZmJwd2l3eHVkbHF1b21hcWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTcxNTEsImV4cCI6MjA1OTY5MzE1MX0.x4Xe0ekseXpxuGeiKh9SqmwtVdYsRNXaafnh2Lo70Ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);